### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by JipDol2** [YujinJung/Portfolio_Game2#1]
안녕하세요.
전 지금 학교 과제로 오픈소스 프로젝트에 참여해야 되는 상황입니다.
그래서 저가 참여할 수 있는 규모의 프로젝트와 제 능력에 벗어나지 않는 프로젝트를 찾다가 여기까지 찾아오게 되었습니다.
작성자님께서 불편하시지 않으시다면 혹시 저가 이 프로젝트에 조심스럽게 참여해도 될까요??
그리고 이 게임을 어떻게 실행시켜야 되는지 잘 모르겠습니다...ㅠ 
감사합니다

**Comment by YujinJung** [comment]
안녕하세요
해당 프로젝트를 마무리하고 다른 공부를 하고 있어 답변이 늦었습니다 ㅠㅠ
제가 게임회사 공채를 준비하고 있고 이제 시험을 준비하고 있어 
이 프로젝트를 당분간 업데이트하거나 관리하기 어려울 것 같습니다..
그래도 괜찮으시다면 당연히 이용해주셔도 괜찮습니다.

실행방법은 (언리얼엔진이 설치되어있으셔야합니다)
1. 저장소를 클론해서 컴퓨터에 저장해주시고
2. Portfolio_Game2.uproject 를 우클릭하셔서 Generate visual studio project files 를 클릭합니다.
![image](https://user-images.githubusercontent.com/20323399/67194844-d6c09c00-f432-11e9-86c6-da9ccb0ff9c6.png)
3. 조금 기다리시면 몇개 폴더와 솔루션파일이 생성됩니다.
![image](https://user-images.githubusercontent.com/20323399/67195609-353a4a00-f434-11e9-8109-770c88ad1c0c.png)
4. 솔루션 파일을 클릭해 visual studio 안에서 코딩해주시면 되고 Portfolio_Game2.uproject 을 클릭해서 언리얼엔진 안에서도 게임을 만들어주시면 됩니다.

게임만 실행하시려는 거면
1. [https://github.com/YujinJung/Portfolio_Game2/releases](url) 에서 WindowsNoEditor.zip
를 다운받아주시고
2. Portfolio_Game2.exe 를 실행해주시면 됩니다.
